### ISSUE TITLE
unable to use this service in node project

### ISSUE THREAD

**Issue by HamzaBinSarfraz** [uport-project/lambda-chasqui#15]
i want to use this service in my node js project but unable to use it, things i tried

- install using **npm install gitRepoURL** (Error: Cannot find module 'lambda-olorun')
- link package using **npm link __dirpath** (Error: Cannot find module 'lambda-olorun')

is there any way i can use this in my project Or any other alternative ?
[Error](https://paste.pics/22edd300c031b7116a194d18b2264c64)
[inside servre.js](https://paste.pics/cb85cdf9809465694e6497c53b90584f)

**node server.js run cmd**

there is main: index.js entry in package.json file but index.js not exist in src dir

**Comment by ajunge** [comment]
Hi. This service is meant to be run independently, not inside another service
